/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package embedded.problem

import embedded.problem.config.Config
import embedded.problem.config.MongoConfig
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest
import org.springframework.test.context.ContextConfiguration
import org.springframework.test.context.TestPropertySource
import spock.lang.Specification

@DataMongoTest
@ContextConfiguration(classes = [MongoConfig, Config])
@TestPropertySource(properties = "property=1")
class FirstTestSuite extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
