/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package embedded.problem

import embedded.problem.config.Config
import embedded.problem.config.MongoConfig
import org.slf4j.Logger
import org.springframework.boot.test.autoconfigure.data.mongo.DataMongoTest
import org.springframework.test.context.ContextConfiguration
import org.springframework.test.context.TestPropertySource
import spock.lang.Specification

@DataMongoTest
@ContextConfiguration(classes = [MongoConfig, Config])
@TestPropertySource(properties = "property=3") //<- if these properties are common between specifications, then everything is ok
class ThirdTestSuite extends Specification {

    def "application has a greeting"() {
        setup:
        def app = new App()

        when:
        def result = app.greeting

        then:
        result != null
        sleep(50000)
    }
}
